### PR TITLE
Enable usage of loadbalancer for frontend in Helm

### PR DESCRIPTION
**Pull request by Younday**
- Enable usage of Loadbalancer directly for frontend 

This however currently requires manually adjusting `frontend_url` in Helm chart after deploying, since the loadbalancer URL is not known at the time of deployment often.

### CODE REVIEW

**Comment by Younday** [comment]
Keeping this PR on hold for now. It would be nicer to have a way where we don't have to adjust the `frontend_url` variable after the deployment. This is possible, but would require some changes on the `backend` application.

**Comment by baranbartu** [comment]
is this for using loadbalancer url to access to the UI?

**Comment by baranbartu** [comment]
> Keeping this PR on hold for now. It would be nicer to have a way where we don't have to adjust the `frontend_url` variable after the deployment. This is possible, but would require some changes on the `backend` application.

Could you help me understand the exact use case and need? As far as I understand, we aim to enable the user to utilize the LoadBalancer, and subsequently, we want them to access the UI URL via its FQDN. Following this, do we intend to let backend knows that this URL is known for CORS?

**Comment by Younday** [comment]
Closing this PR, as I think a change like this will first need some adjustments in the backend application.

**Pull request closed without merging**
